### ISSUE TITLE
Unable to reproduce simple example in Jupyter lab

### ISSUE THREAD

**Issue by hoangthienan95** [flekschas/jupyter-scatter#79] opened 2023-06-25 01:44 UTC
I tried the initial example:

```python
import jscatter

x = np.random.rand(500)
y = np.random.rand(500)

jscatter.plot(x, y)
```
This is what it looks like

<img width="1656" alt="image" src="https://github.com/flekschas/jupyter-scatter/assets/25307953/c5f7a91a-b719-42b3-9add-4bd0db7e3529">

After clicking on box: 
<img width="1658" alt="image" src="https://github.com/flekschas/jupyter-scatter/assets/25307953/6049ce5a-0fae-4ba9-a3a0-2be90faf5f44">

```
The text reads: 
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'JupyterScatterModel' from module 'jupyter-scatter'
Error: No version of module jupyter-scatter is registered
    at f.loadClass (http://fry:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.402424ef4079078b2e0e.js?v=402424ef4079078b2e0e:1:74855)
    at f.loadModelClass (http://fry:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:10729)
    at f._make_model (http://fry:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:7517)
    at f.new_model (http://fry:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:5137)
    at f.handle_comm_open (http://fry:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.1a6d6a3a0542a41bec5a.js?v=1a6d6a3a0542a41bec5a:1:3894)
    at _handleCommOpen (http://fry:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.402424ef4079078b2e0e.js?v=402424ef4079078b2e0e:1:73392)
    at y._handleCommOpen (http://fry:8888/static/lab/jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:1233317)
    at async y._handleMessage (http://fry:8888/static/lab/jlab_core.f68a597bc4700114bad4.js?v=f68a597bc4700114bad4:1:1235307)
```

Here are my package versions:
```
 name         : jupyter-scatter                                       
 version      : 0.12.4                                                
 description  : A scatter plot extension for Jupyter Notebook and Lab 

dependencies
 - ipython *
 - ipywidgets >=7.6,<9
 - jupyter-packaging *
 - jupyterlab-widgets >=1.0,<4
 - matplotlib *
 - numpy *
 - pandas *
 - traittypes >=0.2.1
 - typing-extensions *

 name         : jupyter                                                            
 version      : 1.0.0                                                              
 description  : Jupyter metapackage. Install all the Jupyter components in one go. 

dependencies
 - ipykernel *
 - ipywidgets *
 - jupyter-console *
 - nbconvert *
 - notebook *
 - qtconsole *

 name         : jupyterlab                           
 version      : 4.0.2                                
 description  : JupyterLab computational environment 

dependencies
 - async-lru >=1.0.0
 - importlib-metadata >=4.8.3
 - ipykernel *
 - jinja2 >=3.0.3
 - jupyter-core *
 - jupyter-lsp >=2.0.0
 - jupyter-server >=2.4.0,<3
 - jupyterlab-server >=2.19.0,<3
 - notebook-shim >=0.2
 - packaging *
 - tomli *
 - tornado >=6.2.0
 - traitlets *

jupyter server --version #2.6.0
```

**Comment by flekschas** [comment] 2023-06-25 14:46
Sorry about that. Do you have a reproducible environment that you could share?

I just set up a new environment with jscatter `0.12.4` and jlab `4.0.2` this morning and everything worked as expected. I then tried it with this bare bone environment and everything works as expected too:

```yaml
name: jscatter-py310-jlab4

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10.*
  - pip
  - pip:
    - jupyterlab
    - jupyter-scatter
```

**Comment by flekschas** [comment] 2023-07-17 22:13
I'm closing the ticket as I can't reproduce the issue and neither can @manzt. I'm happy to reopen if you have more information on how to reproduce the issue.

**Closed by flekschas** 2023-07-17 22:13 UTC
Labels: unreproducible
