### ISSUE TITLE
Axis tick values not accurate

### ISSUE THREAD

**Issue by jykr** [flekschas/jupyter-scatter#36] opened 2022-07-29 05:12 UTC
Hi, thanks so much for developing this wonderful package! It's been extremely helpful, and I'd like to report some bug that I encountered. 

I often find the tick label value is different from what I get from the selection. Moreover, the tick label value is not properly adjusted as I zoom in and out. 
For example, the following point which should be close to (0, 0) would move further from the origin when I zoomed out.

![image](https://user-images.githubusercontent.com/28916368/181686864-947e36d5-b59a-4aa8-91ef-770ae1110490.png)
![image](https://user-images.githubusercontent.com/28916368/181687022-a7fa2907-a34a-44ce-99a8-8eb9a00099a6.png)

I'm using the following code to generate above plot.
```
# scatterplot 
scatter = jscatter.Scatter(data=plot_df, x='A', y='B', color_by="group", 
                 width=500, height=500, opacity=0.5)
# output area to display dataframe
out = widgets.Output()

# handler for when "selection" changes from scatterplot
def on_change(change):
    out.clear_output()
    with out:
        indicies = change["new"]
        subset = plot_df.iloc[indicies]
        display(subset)
        
# add change handler to scatterplot widget. 
# `on_change` runs every time the `scatterplot.widget.selection` changes

scatter.size(by='rate', norm=(-0.2, 1))
scatter.color(map = {"NegCtrl":"grey", "PosCtrl_inc":"red",
                         "PosCtrl_dec":"blue", "Variant":"green"})
scatter.widget.observe(on_change, names='selection')
scatter.axes(True, True, labels=True)
scatter.legend(True, position='top-left')
display(scatter.show(), out)
```

**Comment by flekschas** [comment] 2022-07-29 12:36
Thank you for reporting the issue! That's definitely a bug. Which version of jupyter-scatter and browser are you using?

I'll try to get this fixed over the weekend.

**Comment by flekschas** [comment] 2022-08-01 23:14
I found the issue, it's caused by setting a dedicated width. When I remove `width=500` the problem seems to be gone. I'll get started working on a fix.

**Comment by flekschas** [comment] 2022-08-02 00:16
A fix is about to be released. Can you check that `v0.7.1` fixes the issue for you?

**Comment by jykr** [comment] 2022-08-02 19:52
It works! Thanks for the quick fix!

**Comment by flekschas** [comment] 2022-10-04 18:03
Thanks for testing! I am closing the issue now.

**Closed by flekschas** 2022-10-04 18:03 UTC
Labels: bug
